name: War
version: 1.0 (Eisenhower)
description: Lets you create TDM and CTF (warzones) for a more structured PVP experience.
author: tommytony
website: war.tommytony.com
main: bukkit.tommytony.war.War
commands:
# Player commands
  warzones:
    description: Lists the warzones on the server. Each warzone is an independent TDM arena.
    usage: /warzones
  zones:
    description: Shortcut for /warzones.
    usage: /zones
  warzone:
    description: Teleports you to the specified warzone's lobby.
    usage: /warzone ziggy
  zone:
    description: Shortcut for /warzone.
    usage: /zone ziggy
  warhub:
    description: Teleports you to the warhub, if it exists. The warhub offers portals to reach each warzone on the server.
    usage: /warhub
  teams:
    description: Lists the teams in the warzone. Must be standing in zone or in its lobby.
    usage: /teams
  join:
    description: Use to change teams. Must be in zone. If in lobby, use to join a team as an alternative to walking in the team gate.
    usage: /join <diamond/iron/gold/d/i/g>
  leave:
    description: Use to leave a battle or a zone. Teleports you back to the zone lobby. Must be in a team already and inside the zone.
    usage: /leave
  team:
    description: Team chat. 
    usage: /team Leeeroooy!!!
# Warzone maker commands
# 1- Battle-related commands
  nextbattle:
    description: Zone makers only. Zone blocks are restored (from memory). Teams are respawned. Just as if a team's life pool had been exhausted.
    usage: /nextbattle
# 2- Warzone creation commands
  setzone:
    description: Zone makers only. Use to create and adjust the warzone outline. A zone area is defined by its Northwest and Southeast corners, up to the sky and down to adminium. When the second corner is set down correctly, the zone blocks are saved.
    usage: /setzone <northwest/southeast/nw/se>, e.g. first, /setzone ziggy se, then, /setzone ziggy northwest
  savezone:
    description: Zone makers only. Use to persist any aesthetic or practical changes made to the zone after the last save. Puts down a default lobby if there are none already. Use optional named parameters to change zone config. Must be in warzone or lobby. 
    usage: 
        - /savezone  =>  Basic save 
        - /savezone lifepool:8 teamsize:5 maxscore:7 autoassign:on outline:off ff:on blockheads:off spawnstyle:<big/flat/small> unbreakable:on nocreatures:on
        - /savezone loadout:default  =>  sets the respawn inventory to your current items
        - /savezone reward:default  =>  sets the winner's reward to your current items
  setzonelobby:
    description: Zone makers only. Creates or changes the position of the warzone lobby. Must be in warzone or lobby.
    usage: /setzonelobby <north/east/south/west/n/e/s/w>
  setzoneloadout:
    description: Zone makers only. Changes the zone's respawn loadout to your current inventory. Must be in warzone or lobby.
    usage: /setzoneloadout
  setteam:
    description: Zone makers only. Creates or moves a team spawn. The lobby is updated to reflect any new team. The only available teams are diamond, iron and gold. Must be warzone. 
    usage: /setteam <diamond/iron/gold/d/i/g>
  setmonument:
    description: Zone makers only. Creates or moves a monument. Must be in warzone.  
    usage: /setmonument <monument-name>
  setteamflag:
    description: Zone makers only. Creates or moves a team flag post for CTF-style play. The only available teams are diamond, iron and gold. Must be warzone. 
    usage: /setteamflag <diamond/iron/gold/d/i/g>
  resetzone:
    description: Zone makers only. Reloads zone blocks from memory by default. Reloads blocks from disk if "hard" option is added. Sends everyone back to the warzone lobby. Must be in zone or lobby. 
    usage: /resetzone, /resetzone <hard/h>
  deletezone:
    description: Zone makers only. Deletes the zone, resets all blocks. Must be in zone or lobby.  
    usage: /deletezone
  deleteteam:
    description: Zone makers only. Deletes the team. Team must exist. 
    usage: /deleteteam <d/i/g>
  deletemonument:
    description: Zone makers only. Deletes the monument. 
    usage: /deletemonument <monument-name>
  setzoneconfig:
    description: Zone makers only. Use named parameters in any order to change configuration of the zone. Resets blocks like /nextbattle. Does not save zone blocks like /savezone.
    usage: 
        - /setzoneconfig lifepool:8 teamsize:5 maxscore:7 autoassign:on outline:off ff:on blockheads:off spawnstyle:<big/flat/small> unbreakable:on nocreatures:on
        - /setzoneconfig loadout:default  =>  sets the respawn inventory to your current items
        - /setzoneconfig reward:default  =>  sets the winner's reward to your current items
  zonemaker:
    description: Zone makers only. Toggles between player mode and zone maker mode. Or gives/removes access to zonemaker commands for another player. 
    usage: /zonemaker, /zonemaker <new-or-kicked-maker-name>
# 3- War hub
  setwarhub:
    description: Zone makers only. Create or moves a West-facing wall of portals. One portal per warzone. Warzones get a portal back to the warhub.
    usage: /setwarhub
  deletewarhub:
    description: Zone makers only. Deletes the warhub if it exists. Resets all warzone lobbies.
    usage: /deletewarhub
# 4- Defaults
  setwarconfig:
    description: Zone makers only. Change gobal settings and the default warzone configuration values.
    usage: 
        - /setwarconfig pvpinzonesonly:on buildinzonesonly:on  => Global settings 
        - /setwarconfig lifepool:8 teamsize:5 maxscore:7 autoassign:on outline:off ff:on blockheads:off spawnstyle:<big/flat/small> unbreakable:on nocreatures:on  =>  Warzone defaults
        - /setwarconfig loadout:default  =>  sets the respawn inventory to your current items
        - /setwarconfig reward:default  =>  sets the winner's reward to your current items
# Fallback
  war:
    description: Prompts you to use /warhub, /zones and /zone. Can also be used as a prefix for all commands as a fallback if they are taken.
    usage: /war, /war setzone ziggy northwest, /war warhub, /war zone ziggy, etc.
  War:
    description: Same as /war. Used as fallback.
    usage: See /war.    
#Note: When you /disable War with General, all warzone blocks will be reset and artifacts will disappear. 
#      When you /enable War, all blocks will be loaded from disk and the War-related artifacts will reappear.  